version: 2

sources:
  - name: flights
    database: workspace
    schema: flight_analytics
    tables:
      - name: airline
      - name: airports
      - name: arrivals
      - name: cities
      - name: codeshare
      - name: countries
      - name: departure
      - name: flight_details
      - name: routes